library/urls.py
from django.urls import path
from . import views


app_name = 'lib'
urlpatterns = [
	path('',views.index,name='index'),
	path('detail/',views.detail,name='detail'),
	path('addBook/',views.addBook,name='addBook'),
	path('delBook/<int:book_id>',views.deleteBook,name='delBook'),
	path('about/',views.about,name='about'),
	path('project/',views.project,name='project'),
	path('timeless/',views.timeless,name='timeless'),
	path('spider/',views.spider,name='spider'),

	path('test/',views.test,name="test"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf.urls import handler404,handler500
from django.conf.urls.static import static
from . import settings
# import library.views as view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/',include('library.urls')),
]
urlpatterns += static('/static/',document_root=settings.STATIC_ROOT)
# handler404 = view.page_not_found

library/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
	name = models.CharField(max_length=200)
	author = models.CharField(max_length=100)
	pub_house = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

library/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Book
from django.urls import reverse
# Create your views here.
# 主页
def index(request):
	return render(request,"home/index.html")
# 关于
def about(request):
	return render(request,"home/about.html")
# 项目详情
def project(request):
	return render(request,"home/work.html")
# 爬虫使用一种模板
def spider(request):
	return render(request,"spider.html")
# django、appium、笔记使用文章类模板
def django(request):
	return render(request,"home/article.html")
# 时间轴模板
def timeless(request):
	return render(request,"timeless/timeline2.html")

def test(request):
	return render(request,"test.html")






def detail(request):
	book_list = Book.objects.order_by('-pub_date')[:5]
	context = {'book_list':book_list}
	return render(request,'lib/detail.html',context)

def addBook(request):
	if request.method == 'POST':
		temp_name = request.POST['name']
		temp_author = request.POST['author']
		temp_pub_house = request.POST['pub_house']

	from django.utils import timezone
	temp_book = Book(name=temp_name,author=temp_author,pub_house=temp_pub_house,pub_date=timezone.now())
	temp_book.save()

	return HttpResponseRedirect(reverse('lib:detail'))

def deleteBook(request,book_id):
	bookId = book_id
	Book.objects.filter(id=bookId).delete()
	return HttpResponseRedirect(reverse('lib:detail'))

# def page_not_found(request):
# 	from django.shortcuts import render_to_response
# 	response = render_to_response('404.html')
# 	response.status_code = 404
# 	return response
	

library/templates/bottom.html
    {% load static %}
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>瞎写瞎玩瞎看<a href="#"  title="短语"></a></b></p>
				</div>
			
				<div class="col-lg-4">
					<p>too young too simple too naive</p>
				</div>
				<div class="col-lg-4">
					<p>544436626@qq.com</p>
				</div>
			</div>
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="{% static "homepage/js/jquery.min.js" %}"></script>
    <script src="{% static "homepage/js/bootstrap.min.js" %}"></script>
  </body>
</html>

library/templates/home/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <link rel="shortcut icon" href="{% static "homepage/ico/favicon.ico" %}">

    <title>关于</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "homepage/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "homepage/css/style.css" %}" rel="stylesheet">
    <link href="{% static "homepage/css/font-awesome.min.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">这是啥？</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'lib:index' %}">WELCOME</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'lib:index' %}">首页</a></li>
            <li class="active"><a href="{% url 'lib:about' %}">关于</a></li>
            <li><a href="{% url 'lib:index' %}#works">项目</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


	<div id="aboutwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/aboutwrap -->
	
	<div class="container">
		<div class="row centered mt mb">
			<div class="col-lg-8 col-lg-offset-2">
				<h2>PAUL SILVA</h2>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
				<p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
				<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
			</div>

		</div><! --/row -->
	</div><! --/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>WEB DESIGNER, DEVELOPER & GAME ADDICT</b></p>
				</div>
			
				<div class="col-lg-4">
					<p>Living in the amazing London.</p>
				</div>
				<div class="col-lg-4">
					<p>hello@instant.com</p>
				</div>
			
			</div>
		
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="{% static "homepage/js/jquery.min.js" %}"></script>
  </body>
    <script src="{% static "homepage/js/bootstrap.min.js" %}"></script>
  </body>
</html>

library/templates/home/bottom.html
    {% load static %}
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>瞎写瞎玩瞎看<a href="#"  title="短语"></a></b></p>
				</div>
			
				<div class="col-lg-4">
					<p>too young too simple too naive</p>
				</div>
				<div class="col-lg-4">
					<p>544436626@qq.com</p>
				</div>
			</div>
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="{% static "homepage/js/jquery.min.js" %}"></script>
    <script src="{% static "homepage/js/bootstrap.min.js" %}"></script>
  </body>
</html>

library/templates/home/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <link rel="shortcut icon" href="{% static "homepage/ico/favicon.ico" %}">

    <title>练手</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "homepage/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "homepage/css/style.css" %}" rel="stylesheet">
    <link href="{% static "homepage/css/font-awesome.min.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">这是啥？</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'lib:index' %}">WELCOME</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'lib:index' %}">首页</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#project">项目</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- <div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div> -->


	<div id="headerwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<!-- <h4>HELLO PEOPLE, MY NAME IS</h4> -->
					<h1>ZHANG PENGYAO</h1>
					<h4>一个想学前端，了解点开发流程，写了几个小爬虫，做过一两个自动化小程序的机械设计专业的菜鸟测试</h4>
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/headerwrap -->

library/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <link rel="shortcut icon" href="{% static "homepage/ico/favicon.ico" %}">

    <title>练手</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "homepage/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "homepage/css/style.css" %}" rel="stylesheet">
    <link href="{% static "homepage/css/font-awesome.min.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">这是啥？</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'lib:index' %}">WELCOME</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'lib:index' %}">首页</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#project">项目</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- <div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div> -->


	<div id="headerwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<!-- <h4>HELLO PEOPLE, MY NAME IS</h4> -->
					<h1>ZHANG PENGYAO</h1>
					<h4>一个想学前端，了解点开发流程，写了几个小爬虫，做过一两个自动化小程序的机械设计专业的菜鸟测试</h4>
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/headerwrap -->
	
	<section id="project"></section>
	<div class="container">
		<div class="row centered mt mb">
			<h1>分 类</h1>
			
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="{% url 'lib:spider' %}"><img src='{% static "homepage/img/portfolio/spider.png" %}' class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="#project"><img src='{% static "homepage/img/portfolio/appium.png" %}' class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="#project"><img src='{% static "homepage/img/portfolio/django.png" %}' class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="#project"><img src='{% static "homepage/img/portfolio/writing.png" %}' class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="{% url 'lib:timeless' %}"><img src='{% static "homepage/img/portfolio/timeline.png" %}' class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="#project"><img src='{% static "homepage/img/portfolio/last.png" %}' class="img-responsive"></a>
			</div>
		</div><! --/row -->
	</div><! --/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>瞎写瞎玩瞎看<a href="#"  title="短语"></a></b></p>
				</div>
			
				<div class="col-lg-4">
					<p>too young too simple too naive</p>
				</div>
				<div class="col-lg-4">
					<p>544436626@qq.com</p>
				</div>
			</div>
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="{% static "homepage/js/jquery.min.js" %}"></script>
  </body>
    <script src="{% static "homepage/js/bootstrap.min.js" %}"></script>
  </body>
</html>

library/templates/home/work.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <link rel="shortcut icon" href="{% static "homepage/ico/favicon.ico" %}">

    <title>INSTANT - Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "homepage/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "homepage/css/style.css" %}" rel="stylesheet">
    <link href="{% static "homepage/css/font-awesome.min.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'lib:index' %}">INSTANT</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'lib:index' %}">Home</a></li>
            <li><a href="{% url 'lib:about' %}">About</a></li>
            <li><a href="#works">Works</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


	<div id="workwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<h4>NEW WEBSITE FOR</h4>
					<h1>INSTANT</h1>
					<h4>ROLE: LEAD DESIGNER</h4>
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/workwrap -->
	
	<section id="works"></section>
	<div class="container">
		<div class="row centered mt mb">
			<div class="col-lg-8 col-lg-offset-2">
				<h4>ABOUT THE PROJECT</h4>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
			</div>
			<div class="col-lg-10 col-lg-offset-1 mt">
				<img class="img-responsive" src="{% static 'homepage/img/pr01.jpg' %}">
				<br>
				<img class="img-responsive" src="{% static 'homepage/img/pr02.jpg' %}">
			</div>

		</div><! --/row -->
	</div><! --/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>WEB DESIGNER, DEVELOPER & GAME ADDICT</b></p>
				</div>
			
				<div class="col-lg-4">
					<p>Living in the amazing London.</p>
				</div>
				<div class="col-lg-4">
					<p>hello@instant.com</p>
				</div>
			
			</div>
		
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="{% static "homepage/js/jquery.min.js" %}"></script>
  </body>
    <script src="{% static "homepage/js/bootstrap.min.js" %}"></script>
  </body>
</html>

library/templates/lib/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Book List</h1>
	<table>
		<tr>
			<td>书名</td>
			<td>作者</td>
			<td>出版社</td>
			<td>出版时间</td>
		</tr>
	{% for book in book_list.all %}
		<tr>
			<td>{{book.name}}</td>
			<td>{{book.author}}</td>
			<td>{{book.pub_house}}</td>
			<td>{{book.pub_date}}</td>
			<td><a href="{% url 'lib:delBook' book.id %}">删除</a></td>
		</tr>
	{% endfor %}	
	</table>
<form action="{% url 'lib:addBook' %}" method="post" name="addBook">
	{% csrf_token %}
	<p><span>书名：</span><input type="text" name="name"></p>
	<p><span>作者：</span><input type="text" name="author"></p>
	<p><span>出版社：</span><input type="text" name="pub_house"></p>
	<input type="submit" value="添加">
</form>


</body>
</html>

library/templates/lib/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" type="text/css" href="/static/index.css">
	<link rel="stylesheet" type="text/css" href="/static/reset.css">
</head>
<body>
	<div class="header">asdasd
		<!-- 头部，放图 -->
	</div>
	<div class="guide">asdasd
		<!-- 导航 -->
	</div>
	<div class="scroll">asdasd
		<!-- 滚动 -->
	</div>
	<div class="bigbank">asdasd
		<div class="newtopic fl">
			<div class="topiclist"></div>
			<div class="topiclist"></div>
			<div class="topiclist"></div>
			<div class="topiclist"></div>
			<div class="topiclist"></div>
			<div class="topiclist"></div>
		</div>
		<div class="right fl">
			{% load staticfiles %}
			<img src="{% static "lib/tupian.png" %}" alt="图片">

		</div>
	</div>
</body>
</html>